### ISSUE TITLE
AI-Serving not utilizing GPU

### ISSUE THREAD

**Issue by ajertec** [autodeployai/ai-serving#3]
Hello, I got AI Serving Server up and running:
- pulled autodeployai/ai-serving:0.9.0-cuda image,
- started server: `docker run --rm -it -v $(pwd):/opt/ai-serving -p 9090:9090 -p 9091:9091 IMAGE_ID`
(even with `docker run --gpus all --rm -it -v $(pwd):/opt/ai-serving -p 9090:9090 -p 9091:9091 IMAGE_ID`)

However, when trying out mnist example (AIServingMnistOnnxModel.ipynb notebook), or modifying this example and deploying my custom models with gpu optimizations ([https://pypi.org/project/onnxruntime-tools/](https://pypi.org/project/onnxruntime-tools/)) server is not utilizing the GPU, only CPU.

My models metadata:
(this is actually TinyBERT transformer model)
![image](https://user-images.githubusercontent.com/41293217/90411328-e4bf6780-e0ab-11ea-895a-cde6b849532c.png)

Can you provide full example of using the AI-Serving with GPU utilization?

Thank you.

**Comment by scorebot** [comment]
@ajertec Thanks for your issue. It's a defect of the AI-Serving, we will fix it as soon as possible, and let you know once it's done.

**Comment by scorebot** [comment]
@ajertec We have fixed the issue of GPU. Please, try the image `autodeployai/ai-serving:0.9.1-cuda` that if resolve your issue.

**Comment by ajertec** [comment]
@scorebot Thank you, now GPU is being utilized.

**Comment by scorebot** [comment]
Cool. I close it now.
